MediaBundle\Entity\Commentaire:
    type: entity
    oneToMany:
        album:
            targetEntity: MediaBundle\Entity\Album
            mappedBy: commentaire
    table: null
    repositoryClass: MediaBundle\Repository\CommentaireRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        utilisateur:
            type: string
            length: 255
        commentaire:
            type: text
    lifecycleCallbacks: {  }
