_index:
    path:     /
    defaults: { _controller: "MediaBundle:Album:index" }
    methods:  GET

_show:
    path:     /{id}/show
    defaults: { _controller: "MediaBundle:Album:show" }
    methods:  GET

_new:
    path:     /new
    defaults: { _controller: "MediaBundle:Album:new" }
    methods:  [GET, POST]

_edit:
    path:     /{id}/edit
    defaults: { _controller: "MediaBundle:Album:edit" }
    methods:  [GET, POST]

_delete:
    path:     /{id}/delete
    defaults: { _controller: "MediaBundle:Album:delete" }
    methods:  DELETE
